version: '3.8'
services:
  backend:
    build:
      context: ./backend
    container_name: lost_found_backend
    restart: always
    ports:
      - "9001:9001"
    env_file:
      - ./backend/.env
    environment:
      - PORT=9001
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./backend/uploads:/usr/src/app/uploads

  frontend:
    build:
      context: ./frontend
    container_name: lost_found_frontend
    restart: always
    ports:
      - "9000:9000"
    env_file:
      - ./frontend/.env
    environment:
      - NUXT_PORT=9000
      - NUXT_HOST=0.0.0.0
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.nuxt
