-- ==========================================
-- 🔴 1. DROP EXISTING TABLES AND TYPES
-- ==========================================
-- ลบ Table เก่าทิ้งก่อน โดยเรียงลำดับจาก Table ลูก (ที่มี FK) ไปหา Table แม่
DROP TABLE IF EXISTS "AuditLog" CASCADE;
DROP TABLE IF EXISTS "ItemPhoto" CASCADE;
DROP TABLE IF EXISTS "Claim" CASCADE;
DROP TABLE IF EXISTS "Match" CASCADE;
DROP TABLE IF EXISTS "LostItem" CASCADE;
DROP TABLE IF EXISTS "FoundItem" CASCADE;
DROP TABLE IF EXISTS "Locker" CASCADE;
DROP TABLE IF EXISTS "Location" CASCADE;
DROP TABLE IF EXISTS "Category" CASCADE;
DROP TABLE IF EXISTS "Person" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;

-- ลบ Enum Types หากมีอยู่แล้ว
DROP TYPE IF EXISTS person_type_enum CASCADE;
DROP TYPE IF EXISTS found_status_enum CASCADE;
DROP TYPE IF EXISTS lost_status_enum CASCADE;
DROP TYPE IF EXISTS match_status_enum CASCADE;
DROP TYPE IF EXISTS claim_status_enum CASCADE;
DROP TYPE IF EXISTS user_role_enum CASCADE;
DROP TYPE IF EXISTS user_status_enum CASCADE;

-- ==========================================
-- 🟡 2. CREATE ENUM TYPES
-- ==========================================
CREATE TYPE person_type_enum AS ENUM ('STUDENT', 'STAFF', 'EXTERNAL');
CREATE TYPE found_status_enum AS ENUM ('FOUND', 'STORED', 'MATCHED', 'CLAIMED', 'RETURNED', 'EXPIRED');
CREATE TYPE lost_status_enum AS ENUM ('LOST', 'MATCHED', 'CLOSED');
CREATE TYPE match_status_enum AS ENUM ('PENDING', 'CONFIRMED', 'REJECTED');
CREATE TYPE claim_status_enum AS ENUM ('CLAIMED', 'RETURNED', 'CANCELLED');
CREATE TYPE user_role_enum AS ENUM ('ADMIN', 'STAFF');
CREATE TYPE user_status_enum AS ENUM ('Active', 'Inactive');

-- ==========================================
-- 🟢 3. CREATE TABLES
-- ==========================================

-- 1. User
CREATE TABLE "User" (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    role user_role_enum DEFAULT 'STAFF',
    status user_status_enum DEFAULT 'Active',
    last_login TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Person
CREATE TABLE "Person" (
    person_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_type person_type_enum NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    student_id VARCHAR(50),
    email VARCHAR(255),
    phone VARCHAR(50),
    department VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Category
CREATE TABLE "Category" (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(255) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Location
CREATE TABLE "Location" (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_name VARCHAR(255) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE
);

-- 5. Locker
CREATE TABLE "Locker" (
    locker_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locker_code VARCHAR(50) NOT NULL UNIQUE,
    location_id BIGINT REFERENCES "Location"(location_id) ON DELETE SET NULL,
    description TEXT,
    status VARCHAR(50) DEFAULT 'AVAILABLE'
);

-- 6. FoundItem
CREATE TABLE "FoundItem" (
    found_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR(255) NOT NULL,
    category_id BIGINT REFERENCES "Category"(category_id) ON DELETE SET NULL,
    location_id BIGINT REFERENCES "Location"(location_id) ON DELETE SET NULL,
    floor VARCHAR(50),
    found_date DATE,
    description TEXT,
    status found_status_enum DEFAULT 'FOUND',
    locker_id BIGINT REFERENCES "Locker"(locker_id) ON DELETE SET NULL,
    finder_id BIGINT REFERENCES "Person"(person_id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. LostItem
CREATE TABLE "LostItem" (
    lost_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR(255) NOT NULL,
    category_id BIGINT REFERENCES "Category"(category_id) ON DELETE SET NULL,
    location_id BIGINT REFERENCES "Location"(location_id) ON DELETE SET NULL,
    floor VARCHAR(50),
    lost_datetime TIMESTAMP WITH TIME ZONE,
    description TEXT,
    status lost_status_enum DEFAULT 'LOST',
    reporter_id BIGINT REFERENCES "Person"(person_id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. Match
CREATE TABLE "Match" (
    match_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    found_item_id BIGINT REFERENCES "FoundItem"(found_item_id) ON DELETE CASCADE,
    lost_item_id BIGINT REFERENCES "LostItem"(lost_item_id) ON DELETE CASCADE,
    match_score NUMERIC(5, 2),
    status match_status_enum DEFAULT 'PENDING',
    matched_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    matched_by BIGINT REFERENCES "User"(user_id) ON DELETE SET NULL,
    remark TEXT
);

-- 9. Claim
CREATE TABLE "Claim" (
    claim_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    found_item_id BIGINT REFERENCES "FoundItem"(found_item_id) ON DELETE CASCADE,
    claimer_id BIGINT REFERENCES "Person"(person_id) ON DELETE CASCADE,
    claim_date DATE,
    return_date DATE,
    status claim_status_enum DEFAULT 'CLAIMED',
    remark TEXT,
    created_by BIGINT REFERENCES "User"(user_id) ON DELETE SET NULL
);

-- 10. ItemPhoto
CREATE TABLE "ItemPhoto" (
    photo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_type VARCHAR(50) CHECK (item_type IN ('FOUND', 'LOST')),
    item_id BIGINT NOT NULL, -- เก็บ ID ของ FoundItem หรือ LostItem
    file_url TEXT NOT NULL,
    file_name VARCHAR(255),
    is_primary BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 11. AuditLog
CREATE TABLE "AuditLog" (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES "User"(user_id) ON DELETE SET NULL,
    action VARCHAR(50) NOT NULL,
    table_name VARCHAR(50) NOT NULL,
    record_id BIGINT NOT NULL,
    old_value JSONB,
    new_value JSONB,
    ip_address VARCHAR(45),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 🔵 4. INSERT INITIAL DATA
-- ==========================================

-- เพิ่มผู้ใช้งานเริ่มต้น (Admin)
-- หมายเหตุ: ในระบบจริง password_hash ควรถูกเข้ารหัสด้วย bcrypt ก่อนบันทึกลงฐานข้อมูล 
-- (สำหรับทดสอบจะใช้ค่าตรงไปก่อน แต่เมื่อต่อ Backend ควรจะ hash อีกครั้ง)
INSERT INTO "User" (username, password_hash, full_name, email, role, status)
VALUES ('admin', 'admin1234', 'Administrator', 'admin@unifind.local', 'ADMIN', 'Active');
