import { defineStore } from 'pinia';

export const useLangStore = defineStore('lang', {
  state: () => ({
    locale: 'th' as 'th' | 'en',
    translations: {
      en: {
        // Sidebar & Navigation
        'หน้าหลัก': 'Dashboard',
        'รายการทั้งหมด': 'All Items',
        'ของหาย': 'Lost Items',
        'พบของ': 'Found Items',
        'คืนแล้ว': 'Claimed Items',
        'ตู้เก็บของ': 'Lockers',
        'รายงาน': 'Reports',
        'วิเคราะห์จับคู่': 'AI Matching',
        'ประวัติการดำเนินการ': 'Action History',
        'จัดการผู้ใช้': 'Manage Users',
        'การตั้งค่าระบบ': 'System Settings',
        'ออกจากระบบ': 'Logout',
        'Admin Portal': 'Admin Portal',
        'UTCC Unifind': 'UTCC Unifind',

        // General Actions & Common UI
        'บันทึก': 'Save',
        'ยกเลิก': 'Cancel',
        'ยืนยัน': 'Confirm',
        'ปิด': 'Close',
        'แก้ไข': 'Edit',
        'ลบ': 'Delete',
        'ค้นหา': 'Search',
        'กรอง': 'Filter',
        'สถานะ': 'Status',
        'วันที่': 'Date',
        'ชื่อ': 'Name',
        'รายละเอียด': 'Details',
        'รูปภาพ': 'Image',
        'สถานที่': 'Location',
        'หมวดหมู่': 'Category',
        'ตกลง': 'OK',
        'จัดการ': 'Action',
        'ว่าง': 'Empty',
        'เก็บของ': 'Stored',
        'คืนเงิน': 'Refund',
        'ไม่มีข้อมูล': 'No Data Available',
        'บันทึกสำเร็จ': 'Saved Successfully',
        'เกิดข้อผิดพลาด': 'An Error Occurred',
        'ความมั่นใจ': 'Confidence',
        'เหตุผล': 'Reason',
        'หมายเหตุ': 'Note',
        'กำลังส่งข้อมูล': 'Submitting...',
        'รหัสสิ่งของ': 'Item ID',
        'ชื่อสิ่งของ': 'Item Name',
        'สถานะสิ่งของ': 'Item Status',
        'รายละเอียดคำอธิบายของ': 'Description Details',
        'ไม่มีรายละเอียดคำอธิบายของ': 'No description provided',
        'ผู้พบ': 'Finder',
        'ผู้พบ/ส่ง': 'Finder/Reporter',
        'ผู้แจ้ง': 'Reporter',
        'ผู้บันทึก': 'Recorded By',
        'วันที่พบ': 'Date Found',
        'วันที่แจ้ง': 'Date Reported',
        'วันที่บันทึก': 'Date Recorded',
        'ส่งคืนสิ่งของ': 'Return Item',
        'รายละเอียดเพิ่มเติม': 'More Details',
        'ส่งข้อมูลไปทาง Line Bot แจ้งเตือนคู่กรณี': 'Send notification alert to user via LINE Bot',
        'ข้อมูลผู้รับคืน': 'Claimant Information',
        'ชื่อผู้รับคืน': 'Claimant Name',
        'เบอร์โทรติดต่อ': 'Phone Number',
        'อีเมลติดต่อ': 'Contact Email',
        'หลักฐานการรับคืน': 'Claim Proof/Notes',
        'บันทึกการส่งคืน': 'Save Return Status',
        'หลักฐานรูปภาพ': 'Proof Image',

        // Login & Register Pages
        'เข้าสู่ระบบ': 'Login',
        'ชื่อผู้ใช้': 'Username',
        'รหัสผ่าน': 'Password',
        'กรุณากรอกชื่อผู้ใช้': 'Please enter username',
        'กรุณากรอกรหัสผ่าน': 'Please enter password',
        'ชื่อผู้ดูแลระบบ': 'Admin Name',
        'เข้าสู่ระบบแอดมิน': 'Admin Login',
        'ยินดีต้อนรับสู่ระบบ': 'Welcome to the System',
        'ระบบจัดการของหายและส่งคืนสิ่งของ': 'Lost & Found Management System',
        'สำนักกิจการนักศึกษา มหาวิทยาลัยหอการค้าไทย': 'Office of Student Development, UTCC',
        'สมัครสมาชิกเจ้าหน้าที่': 'Staff Registration',
        'ระบบบันทึกของหาย': 'Lost & Found System',
        'ลงทะเบียนสิทธิ์เข้าใช้งาน': 'Register for Access Permission',
        'สำหรับเจ้าหน้าที่จัดการข้อมูล': 'For Data Management Staff',
        'ชื่อผู้ใช้เจ้าหน้าที่': 'Staff Username',
        'เข้าสู่ระบบเจ้าหน้าที่': 'Staff Login',
        'กำลังเข้าสู่ระบบ...': 'Logging in...',
        'ยังไม่มีบัญชีเจ้าหน้าที่?': 'Don\'t have a staff account?',
        'สมัครสมาชิกที่นี่': 'Register here',
        'ชื่อผู้ใช้งาน (Username) *': 'Username *',
        'ชื่อเล่น': 'Nickname',
        'ชื่อเล่น (Nickname)': 'Nickname',
        'ชื่อเล่น (Nickname) *': 'Nickname *',
        'อีเมลติดต่อ (Email) *': 'Contact Email *',
        'รหัสผ่าน (Password) *': 'Password *',
        'ยืนยันรหัสผ่าน *': 'Confirm Password *',
        'กำลังสมัครสมาชิก...': 'Registering...',
        'ส่งคำขอสมัครสมาชิก': 'Submit Registration Request',
        'มีบัญชีเจ้าหน้าที่อยู่แล้ว?': 'Already have a staff account?',
        'เข้าสู่ระบบที่นี่': 'Login here',
        'สิทธิ์ในการตั้งค่าระบบถูกจำกัดเฉพาะบัญชีผู้ดูแลพิเศษเท่านั้น': 'System settings are restricted to Super Administrator accounts only.',
        'ขออภัย บัญชีของคุณไม่มีสิทธิ์ในการเข้าถึงหน้าตั้งค่าระบบ': 'Sorry, your account does not have permission to access Settings.',
        'ข้อมูลผู้ใช้งาน': 'User Information',
        'อีเมลผู้ใช้งาน:': 'User Email:',
        'การเชื่อมต่อเซิร์ฟเวอร์': 'Server Connection',
        'API Base Endpoint:': 'API Base Endpoint:',
        'ฐานข้อมูลระบบ (Supabase SQL):': 'Database Status (Supabase SQL):',
        'การแจ้งเตือน': 'Notifications',
        'ส่งข้อความแจ้งเตือนหาเจ้าของผ่าน Line Official Account โดยอัตโนมัติ': 'Automatically send alert notifications via Line Official Account',
        'ส่งอีเมลสรุปยอดของหายประจำสัปดาห์ให้กับคณะบดี': 'Send weekly lost item summary email to the Dean',
        '⚠️ Zone อันตราย': '⚠️ Danger Zone',
        '🚪 ออกจากระบบ (Logout)': '🚪 Logout',

        // Dashboard
        'ภาพรวมระบบ Lost & Found': 'Lost & Found Dashboard',
        'ภาพรวมสถานะและสถิติของระบบ': 'System Overview and Status Statistics',
        'ช่วงเวลา: ทั้งหมด': 'Period: All Time',
        'ช่วงเวลา: 30 วันล่าสุด': 'Period: Last 35 Days',
        'ช่วงเวลา: 90 วันล่าสุด': 'Period: Last 90 Days',
        'ช่วงเวลา: 180 วันล่าสุด': 'Period: Last 180 Days',
        'ช่วงเวลา: 1 ปีล่าสุด': 'Period: Last Year',
        'หมวดหมู่: ทั้งหมด': 'Category: All',
        'สถานที่: ทั้งหมด': 'Location: All',
        'ของหาย (Lost)': 'Lost Items',
        'ของพบ / ยังไม่เคลม': 'Found / Unclaimed',
        'ส่งคืนแล้ว (Claimed)': 'Claimed Items',
        'สถานะรายการ': 'Item Status Statistics',
        'รายการ': 'Items',
        'สถิติรายเดือน': 'Monthly Trends',
        'รายการล่าสุด': 'Recent Items',
        'รายการของหายและของพบล่าสุด': 'Latest Lost and Found Items',
        'ดูทั้งหมด': 'View All',
        'สวัสดีตอนเช้า': 'Good morning',
        'สวัสดีตอนบ่าย': 'Good afternoon',
        'สวัสดีตอนเย็น': 'Good evening',
        'ตอนเช้า': 'Morning',
        'ตอนบ่าย': 'Afternoon',
        'ตอนเย็น': 'Evening',
        'รายการที่ต้องดำเนินการล่าสุด': 'Recent Action Logs',
        'ประวัติกิจกรรมทั้งหมดในระบบ': 'All Activity Logs in the System',

        // Lockers Page
        'ผังการจัดเก็บตู้ล็อกเกอร์ (Locker Room Map)': 'Locker Room Map',
        'ตู้ L01–L12 ตามเดือน และตู้เพิ่มเติม —แต่ละตู้มี 2 ชั้น (01, 02) — คลิกชั้นเพื่อดูรายการสิ่งของ': 'Locker L01-L12 by month and extra lockers — 2 floors per locker (01, 02) — Click floor to view items',
        'เพิ่มตู้ล็อกเกอร์': 'Add Locker',
        'ช่องว่าง': 'Empty Slots',
        'ช่องที่ใช้งาน': 'Occupied Slots',
        'ช่องทั้งหมด ({count} ตู้ × 2 ชั้น)': 'Total Slots ({count} Lockers × 2 Floors)',
        'ลบตู้ล็อกเกอร์นี้': 'Delete this locker',
        'ต้องการลบตู้ล็อกเกอร์ {id} หรือไม่?': 'Do you want to delete locker {id}?',
        'ตู้ {id}': 'Locker {id}',
        'ชั้น {num}': 'Floor {num}',
        'ชั้น {floor} — {count} รายการในช่องนี้': 'Floor {floor} — {count} items in this slot',
        'ไม่มีสิ่งของในชั้นนี้': 'No items on this floor',
        'ช่องล็อกเกอร์ {id} ยังว่างอยู่ พร้อมสำหรับจัดเก็บสิ่งของที่พบเจอใหม่': 'Locker slot {id} is empty, ready for storing newly found items',
        'รายการสิ่งของที่จัดเก็บ ({count})': 'Stored Items ({count})',
        'ปิดหน้าต่าง': 'Close Window',
        'เพิ่มตู้ล็อกเกอร์ใหม่': 'Add New Locker',
        'เพิ่มพื้นที่จัดเก็บใหม่ให้กับระบบ': 'Add a new storage space to the system',
        'รหัสตู้ล็อกเกอร์': 'Locker ID',
        'ป้ายกำกับ / คำอธิบายตู้': 'Locker Label / Description',
        'เลือกเดือนหรือป้ายกำกับ': 'Select month or label',
        'กรอกหมายเลขตู้ เช่น 13, 14, 15': 'Enter locker number, e.g. 13, 14, 15',
        'รหัสตู้ล็อกเกอร์ {id} มีอยู่ในระบบแล้ว': 'Locker ID {id} already exists in the system',
        'กรุณากรอกหมายเลขตู้': 'Please enter locker number',
        'บันทึกตู้ใหม่': 'Save Locker',
        'ใช้งานอยู่': 'Occupied',
        'รายละเอียดช่องเก็บของ {id}': 'Locker Slot {id} Details',
        'ช่องล็อกเกอร์ยังว่างอยู่': 'Locker slot is empty',
        '{count} รายการ': '{count} Items',

        // Items Page & Filters
        'ค้นหาด้วยรหัสสิ่งของ หรือ ชื่อสิ่งของ...': 'Search by Item ID or Name...',
        'หมวดหมู่ทั้งหมด': 'All Categories',
        'สถานที่ทั้งหมด': 'All Locations',
        'สถานะทั้งหมด': 'All Statuses',
        'ข้อมูลผู้แจ้งและพบ': 'Reporter & Finder Info',
        'ชื่อผู้พบของ': 'Finder Name',
        'ชื่อผู้แจ้งของหาย': 'Reporter Name',
        'ตู้จัดเก็บ': 'Locker ID',
        'รายละเอียดคำอธิบาย': 'Description',
        'ไม่มีรูปภาพ': 'No Image Available',
        'รูปภาพสิ่งของ': 'Item Image',
        'ประเภทสิ่งของ': 'Item Type',
        'ประเภท': 'Type',
        'ข้อมูลผู้รับของ': 'Receiver Information',
        'ชื่อผู้รับของ': 'Receiver Name',
        'หลักฐานการรับของ': 'Proof / Notes',
        'ผู้ส่งคืน': 'Returned By',
        'วันที่ส่งคืน': 'Date Returned',
        'ยังไม่ระบุ': 'N/A',

        // AI Matching Page
        'วิเคราะห์จับคู่ด้วย AI': 'AI Matching Analysis',
        'ระบบวิเคราะห์เปรียบเทียบข้อมูลอัตโนมัติด้วยระบบคู่ประสาท AI (Gemini)': 'Automatic matching analysis powered by Gemini AI network',
        'รายการแจ้งของหายในระบบ': 'Lost Items in System',
        'เลือกรายการของหายเพื่อวิเคราะห์': 'Select a Lost Item to Analyze',
        'ไม่มีสิ่งของรอจับคู่': 'No items waiting to be matched',
        'เริ่มวิเคราะห์ด้วย AI': 'Analyze with AI',
        'คู่ข้อมูลที่ใกล้เคียงจากคลังของพบ': 'Closest Matches from Stored Found Items',
        'กด "เริ่มวิเคราะห์ด้วย AI" เพื่อค้นหารายการที่ใกล้เคียง': 'Click "Analyze with AI" to find matching items',
        'คำนวณความมั่นใจ': 'Calculating Confidence...',
        'ความคล้ายคลึง': 'Similarity Score',
        'สถานะคำแนะนำ': 'Recommendation Status',

        // Action logs & User Management
        'ชื่อผู้รับผิดชอบ': 'Authorized Admin',
        'รายละเอียดประวัติ': 'Action Details',
        'บทบาทแอดมิน': 'Admin Role',
        'บทบาท': 'Role',
        'จัดการสมาชิก': 'Manage Members',
        'จัดการบัญชีและระดับสิทธิ์การทำงาน': 'Manage Accounts and Permission Levels',
        'เพิ่มผู้ใช้งาน': 'Add User',
        'อีเมล': 'Email',
        'ระดับสิทธิ์': 'Role Level',
        'ลบผู้ใช้': 'Delete User',
        'ลบบัญชีผู้ใช้': 'Delete User Account',
        'ต้องการลบผู้ใช้งาน': 'Are you sure you want to delete user',
        'หรือไม่?': '?',

        // Floating Action Buttons (FABs) & Success Alerts
        'แจ้งบันทึกของหาย (Lost Item)': 'Report Lost Item',
        'แจ้งพบของส่งเข้าคลัง (Found Item)': 'Report Found Item',
        'สแกน QR Code ติดตามของ': 'Scan QR Code',
        'กล้องสแกนติดตามสิ่งของ (QR Code Scanner)': 'QR Code Scanner',
        'จัดวาง QR Code ในกรอบ': 'Align QR Code inside frame',
        'ระบบจะเปิดใช้งานเว็บแคมเพื่อสแกน QR Code สำหรับสืบค้นรหัสสิ่งของสูญหาย': 'System will activate webcam to scan QR Code for Item ID lookup',
        'ปิดระบบกล้อง': 'Close Camera',
        'AI ตรวจพบสิ่งของใกล้เคียงในระบบ!': 'AI found matching items in the system!',
        'ตรวจวิเคราะห์อัตโนมัติด้วยระบบ Gemini AI': 'Analyzed automatically via Gemini AI',
        'เปอร์เซ็นต์ความคล้ายคลึงของข้อมูล': 'Similarity Match Confidence',
        'รายการที่คุณบันทึกใหม่': 'Your New Entry',
        'หมวดหมู่: {cat}': 'Category: {cat}',
        'พบข้อมูลที่ตรงกันในระบบ': 'Matched System Records',
        'ผู้แจ้ง: {reporter}': 'Reporter: {reporter}',
        'ID: {id}': 'ID: {id}',
        'วันที่: {date}': 'Date: {date}',
        'ระบบได้ส่งข้อความแจ้งเตือนด่วนผ่าน LINE Bot ไปยังคู่กรณีเรียบร้อยแล้ว แนะนำให้ตรวจสอบหลักฐานความเป็นเจ้าของก่อนรับของคืน': 'The system has dispatched an alert to the owner via LINE Bot. Please verify proof of ownership before returning.',
        'ตกลงและรับทราบ': 'OK & Acknowledge',
        'แจ้งเรื่องของหายสำเร็จ!': 'Lost Item Reported Successfully!',
        'แจ้งเรื่องของหายสำเร็จ': 'Lost Item Reported Successfully',
        'บันทึกข้อมูลแจ้งพบของส่งเข้าคลังเรียบร้อยแล้ว': 'Successfully recorded found item entry in storage.',
        'ได้จัดทำข้อมูลแจ้งพบของส่งเข้าคลังเรียบร้อยแล้ว': 'Successfully recorded found item entry in storage.',
        'ได้จัดทำข้อมูลแจ้งเรื่องของหายเข้าสู่ระบบเรียบร้อยแล้ว': 'Successfully recorded lost item entry in system.',
        'เกิดข้อผิดพลาดในการบันทึกข้อมูล': 'An error occurred while saving information.',
        'กรุณาเข้าสู่ระบบก่อนเข้าใช้งานหน้านี้': 'Please log in to access this page',

        // Return Item Form Specifics
        'ชื่อ-นามสกุล ผู้รับคืน': 'Recipient Full Name',
        'ประเภทบุคคล': 'Person Type',
        'นักศึกษา': 'Student',
        'บุคลากร': 'Staff',
        'บุคคลภายนอก': 'External',
        'รหัสนักศึกษา': 'Student ID',
        'เบอร์โทรศัพท์ติดต่อ': 'Phone Number',
        'อีเมล (ถ้ามี)': 'Email (Optional)',
        'ความสัมพันธ์กับสิ่งของ': 'Relationship with Item',
        'เป็นเจ้าของสิ่งของ (Owner)': 'Is the Owner',
        'เป็นผู้แทนมารับคืน (Representative)': 'Is a Representative',
        'หมายเหตุ / บันทึกการส่งมอบ': 'Notes / Handover Record',
        'ยืนยันการคืนของ': 'Confirm Return',
        'ตู้ล็อกเกอร์:': 'Locker:',
        'คืนของ': 'Return',
        'รายการพบของ': 'Found Items',
        'พร้อมคืน': 'Ready to Return',

        // Revert Form / Claimed Page Specifics
        'นำกลับไปยังคลัง': 'Revert to Storage',
        'นำสิ่งของกลับไปยังคลัง': 'Return Item to Storage',
        'กรอกเหตุผลเพื่อบันทึกประวัติการนำสิ่งของกลับเข้าคลัง': 'Enter reason to record reversion to storage history',
        'เหตุผลในการนำกลับ': 'Reason for Return',
        'ระบุเหตุผล เช่น ลูกค้าแจ้งยกเลิกการรับของ, ข้อมูลบันทึกผิดพลาด...': 'e.g., Owner cancelled claim, incorrect entry info...',
        'ยืนยันนำกลับคลัง': 'Confirm Return to Storage',
        'ยังไม่มีรายการที่คืนเจ้าของ': 'No claimed items yet',
        'คืนสำเร็จ': 'Claimed Successfully',
        'เพิ่มประเภท': 'Add Category',
        'เพิ่มสถานที่': 'Add Location',
        'เลือกสถานที่พบ': 'Select Location Found',
        'เลือกประเภทหมวดหมู่': 'Select Category',
        'ไม่ระบุตู้': 'No Locker',
        'ไม่ระบุตู้ล็อกเกอร์': 'No Locker Specified',
        'ย้อนกลับ': 'Back',
        'แก้ไขข้อมูล': 'Edit Info',

        // CreateItemModal Specifics
        'แจ้งสิ่งของที่พบ': 'Report Found Item',
        'แก้ไขข้อมูลสิ่งของที่พบ': 'Edit Stored Item',
        'กรุณากรอกข้อมูลให้ครบถ้วนเพื่อความรวดเร็วในการติดตาม': 'Please fill out all details for quick tracking.',
        'ข้อมูลสิ่งของ': 'Item Information',
        'หมวดหมู่สิ่งของ': 'Item Category',
        'สถานที่พบ': 'Location Found',
        'ระบุสถานที่พบเอง': 'Specify Custom Location',
        'วันและเวลาที่พบ': 'Date & Time Found',
        'ระบุตำหนิ สี สติกเกอร์ หรือจุดสังเกตเฉพาะ...': 'e.g., color, unique sticker, mark...',
        'ข้อมูลผู้พบส่ง': 'Finder / Reporter Info',
        'ชื่อผู้พบส่ง': 'Finder Name',
        'ประเภทสถานะผู้พบ': 'Finder Status / Type *',
        'พนักงาน / อาจารย์': 'Staff / Professor',
        'แม่บ้าน': 'Maid / Housekeeper',
        'เจ้าหน้าที่รักษาความปลอดภัย': 'Security Guard',
        'เบอร์โทรศัพท์ติดต่อ *': 'Phone Number *',
        'เลขทะเบียนนักศึกษา *': 'Student ID *',
        'อีเมลมหาวิทยาลัย *': 'University Email *',
        'ข้อมูลการจัดเก็บ': 'Storage Information',
        'รูปภาพสิ่งของ *': 'Item Image *',
        'คลิกหรือลากไฟล์มาวางที่นี่': 'Click or drag file here',
        'รองรับไฟล์ JPG, JPEG, PNG (ขนาดไม่เกิน 10MB)': 'Supports JPG, JPEG, PNG (Max 10MB)',
        'ตู้ล็อกเกอร์ที่จัดเก็บ': 'Storage Locker',
        '(เดือนจากวันที่พบจะถูกเลือกอัตโนมัติ)': '(Month of find date selected automatically)',
        'รหัสตู้ที่จะบันทึก:': 'Locker Code to Save:',
        'ข้อมูลของคุณจะถูกเก็บเป็นความลับ': 'Your information will be kept confidential',
        'ข้อมูลทั้งหมดจะถูกนำไปใช้เพื่อการติดตามสิ่งของเท่านั้น และจะไม่เปิดเผยต่อบุคคลภายนอก': 'All information is strictly used for lost and found tracking and won\'t be shared.',
        'กำลังบันทึกข้อมูล...': 'Saving data...',
        'บันทึกการแก้ไข': 'Save Edits',
        'บันทึกข้อมูล': 'Save Info',

        // ReportLostItemModal Specifics
        'แก้ไขข้อมูลบันทึกของหาย': 'Edit Lost Item Report',
        'แจ้งข้อมูลบันทึกของหาย': 'Report Lost Item',
        'กรุณากรอกข้อมูลให้ครบถ้วนเพื่อความรวดเร็วในการติดตามสิ่งของ': 'Please fill out all details for quick tracking.',
        'ข้อมูลสิ่งของที่หาย': 'Lost Item Information',
        'สถานที่สูญหาย (ตึก/อาคาร)': 'Location Lost (Building)',
        'ไม่ระบุสถานที่ (หรือยังไม่ทราบ)': 'Not Specified (Or Unknown)',
        'อื่นๆ (ระบุเอง)': 'Other (Specify Custom)',
        'ระบุสถานที่หายเอง': 'Specify Custom Location Lost',
        'ระบุสถานที่ เช่น อาคารเรียน 3 ห้อง 302': 'e.g., Building 3, Room 302',
        'ชั้นที่หาย': 'Floor',
        'เช่น ชั้น 1, ชั้น 4': 'e.g., 1st Floor, 4th Floor',
        'วันและเวลาที่คาดว่าหาย': 'Estimated Date & Time Lost',
        'รายละเอียดเพิ่มเติม / จุดสังเกตสิ่งของ': 'More Details / Unique Characteristics',
        'ระบุตำหนิ สี แบรนด์ หรือจุดสังเกตเฉพาะ...': 'e.g., unique color, brand, mark...',
        'ข้อมูลผู้แจ้งทำของหาย': 'Lost Item Reporter Information',
        'ชื่อผู้แจ้งหาย': 'Reporter Name',
        'ประเภทผู้ทำของหาย': 'Reporter Type',
        'เลขทะเบียนนักศึกษา': 'Student ID',
        'อีเมลมหาวิทยาลัย': 'University Email',
        'รูปภาพประกอบ (ถ้ามี)': 'Attach Image (If Any)',
        'เลือกไฟล์': 'Choose File',
        'ข้อมูลทั้งหมดจะถูกนำไปใช้เพื่อการติดตามของหายเท่านั้น และจะไม่เปิดเผยต่อบุคคลภายนอก': 'All information is strictly used for lost and found tracking and won\'t be shared.',
        'ลงทะเบียนของหาย': 'Register Lost Item',

        // AI Matching Page Specifics
        'AI Matching Center (ศูนย์วิเคราะห์และจับคู่สิ่งของหาย)': 'AI Matching Center',
        'เปรียบเทียบสิ่งของที่แจ้งหายและของที่พบในระบบด้วย Gemini AI วิเคราะห์ความน่าจะเป็นในการจับคู่แบบสองทิศทาง': 'Compare lost item reports and found items in storage using Gemini AI to analyze match probability',
        'ของหายรอคู่': 'Lost Items Waiting',
        'ของในคลังรอคืน': 'Found Items Stored',
        '1. เลือกรายการของหาย (Lost Items)': '1. Select Lost Item',
        'ค้นหาของหาย...': 'Search lost items...',
        'ไม่พบรายการของหาย': 'No lost items found',
        '2. เลือกของในคลังเปรียบเทียบ (Found Items)': '2. Select Stored Found Item',
        'ค้นหาของพบเจอ...': 'Search found items...',
        'กรุณาเลือกรายการของหายก่อน': 'Please select a lost item first',
        'ระบบจะแสดงรายชื่อของพบที่อยู่ในหมวดหมู่เดียวกันขึ้นมาเปรียบเทียบแบบอัตโนมัติ': 'The system will show found items in the same category automatically for comparison.',
        'ไม่มีสิ่งของที่พบเจอในหมวดหมู่เดียวกัน': 'No found items in the same category',
        '3. โต๊ะเปรียบเทียบข้อมูลคู่จับคู่': '3. Comparison Table',
        'ฝั่งแจ้งของหาย': 'Lost Item Reporter',
        'ยังไม่เลือกรายการ': 'Not Selected',
        'ฝั่งคลังสิ่งของพบเจอ': 'Stored Found Item',
        'วิเคราะห์ความเข้ากันด้วย AI': 'Analyze Match with AI',
        'กำลังวิเคราะห์ด้วย Gemini AI...': 'Analyzing with Gemini AI...',
        'กำลังอ่านข้อมูลประมวลผล...': 'Processing data...',
        'Gemini AI กำลังวิเคราะห์ชื่อ ตำหนิ สถานที่และวันเวลาสูญหาย': 'Gemini AI is analyzing name, characteristics, location and time lost.',
        'มีโอกาสสูงที่จะเป็นของชิ้นเดียวกัน': 'High match probability',
        'ยังไม่ตรงกันเพียงพอ': 'Low match probability',
        'ข้อวินิจฉัยจาก AI:': 'AI Analysis Diagnosis:',
        'ทำเรื่องคืนของ': 'Process Return',

        // Reports Page Specifics
        'รายงานและสถิติภาพรวม': 'Reports & Statistics Overview',
        'วิเคราะห์ข้อมูลความสำเร็จ สถิติจำนวนของหาย และประสิทธิภาพคลังสินค้า': 'Analyze success data, lost item statistics, and warehouse efficiency',
        'ของหายแจ้งใหม่': 'New Lost Items',
        'สิ่งของที่พบเจอ': 'Found Items Reported',
        'ส่งมอบคืนสำเร็จ': 'Claimed Successfully',
        'อัตราความสำเร็จในการส่งคืน': 'Return Success Rate',
        'ของหายที่ถูกนำส่งคืนเจ้าของสำเร็จ': 'Lost items successfully returned to owner',
        'สำเร็จ {claimed} จากของที่พบเจอ {found} ชิ้น': 'Succeeded {claimed} out of {found} found items',
        'ระยะเวลาเฉลี่ยในการเก็บรักษา': 'Average Retention Time',
        'เวลาเฉลี่ยในการฝากเก็บสิ่งของก่อนเจ้าของมารับคืน': 'Average storage time before owner claim',
        'วัน': 'Days',
        'อ้างอิงจากข้อมูลส่งคืนสำเร็จในระบบ': 'Based on successful return data in system',
        'ระบบจัดเก็บรวดเร็วและปลอดภัย': 'Fast and secure storage system',
        'อัตราการบันทึกจัดเก็บสิ่งของ (Storage Rate)': 'Storage Recording Rate',
        'ของที่พบเจอและนำเข้าจัดเก็บในล็อกเกอร์': 'Found items recorded and stored in lockers',
        'ใช้งานล็อกเกอร์: {occupied} / 12 ตู้': 'Locker usage: {occupied} / 12 lockers',
        'จำแนกตามหมวดหมู่สิ่งของ': 'Breakdown by Item Category',
        'จำแนกตามสถานที่พบเจอ': 'Breakdown by Location Found',
        'วิเคราะห์จุดเสี่ยงของหายบ่อยสุด': 'Risk analysis of most frequent locations lost',
        'สถิติสิ่งของค้างคลังเกณฑ์เกิน 30 วัน': 'Items Stored Exceeding 30 Days',
        'รายการของหาย/ของพบในระบบ': 'Lost & Found System Records',
        'นำส่งเข้าจัดเก็บระบบ': 'Added to storage',
        'คืนเจ้าของเรียบร้อยแล้ว': 'Successfully returned to owner',
        'ผลรวมธุรกรรมทั้งสิ้น': 'Total transactions sum',
        'รายงานสรุปข้อมูลสิ่งของสูญหายและประสิทธิภาพระบบ': 'Summary report of lost items and system performance',
        'พิมพ์เมื่อ:': 'Printed on:',
        'ช่วงเวลาที่เลือก:': 'Selected Period:',
        'เริ่มต้น': 'Start',
        'สิ้นสุด': 'End',
        'ไม่พบข้อมูลรายงานในช่วงเวลาที่ท่านเลือก ({periodLabel})': 'No report data found in selected period ({periodLabel})',
        'กรุณาเลือกช่วงเวลาอื่น หรือตรวจสอบการเชื่อมต่อข้อมูล': 'Please select another period or verify connection.',
        'รายงานของค้างส่งคืน (Unclaimed Items)': 'Unclaimed Items Report',
        'สิ่งของที่พบแต่ไม่มีผู้มารับคืนและตกค้างในคลังมากกว่า 30 วัน': 'Items found but unclaimed and stored in warehouse for more than 30 days.',
        'ระยะเวลาค้างคลัง': 'Storage Duration',
        'ไม่มีตู้': 'No Locker',

        // History Page Specifics
        'บันทึกข้อมูลสิ่งของ': 'Recorded Item',
        'ลงบันทึกโดย': 'Recorded By',
        'สูญหาย': 'Lost',
        'พร้อมส่งคืน': 'Ready to Return',
        'ไม่มีรายการกิจกรรมในระบบ': 'No activity logs in the system',

        // Users Page Specifics
        'จัดการผู้ใช้งานระบบ': 'Manage Users',
        'จัดการสิทธิ์เข้าใช้งาน บัญชีเจ้าหน้าที่ และตรวจสอบคำขอลงทะเบียนเข้าใช้งานระบบ': 'Manage permissions, staff accounts, and registration requests.',
        'เพิ่มผู้ใช้งานใหม่': 'Add New User',
        'ขออภัย บัญชีของคุณไม่มีสิทธิ์ในการเข้าถึงหน้าจัดการผู้ใช้': 'Sorry, your account does not have access to Manage Users.',
        'เฉพาะผู้ดูแลระบบ (Admin) เท่านั้นที่สามารถจัดการบัญชีผู้ใช้ได้': 'Only system Administrators (Admin) can manage user accounts.',
        'เจ้าหน้าที่ในระบบ ({count})': 'Active Staff ({count})',
        'คำขออนุมัติสิทธิ์ ({count})': 'Pending Requests ({count})',
        'ค้นหาผู้ใช้...': 'Search users...',
        'บัญชีเจ้าหน้าที่ (Active Staff & Admins)': 'Active Staff & Admins Accounts',
        'ชื่อผู้ใช้งาน (Username)': 'Username',
        'อีเมล (Email)': 'Email',
        'ระดับสิทธิ์ (Role)': 'Role',
        'สถานะ (Status)': 'Status',
        'วันที่บันทึกระบบ': 'Recorded Date',
        'จัดการบัญชี': 'Manage Account',
        'พร้อมใช้งาน': 'Active',
        'ระงับชั่วคราว': 'Suspended',
        'ระงับ': 'Suspend',
        'เปิดใช้': 'Activate',
        'ไม่พบบัญชีเจ้าหน้าที่ในระบบ': 'No staff accounts found in system.',
        'คำขอลงทะเบียนเข้าใช้งานใหม่ (Pending Registration)': 'Pending Registration Requests',
        'ชื่อผู้สมัคร (Username)': 'Applicant Username',
        'อีเมลติดต่อ (Email)': 'Contact Email',
        'ระดับสิทธิ์ที่ขอ': 'Requested Role',
        'สถานะดำเนินการ': 'Status',
        'วันที่สมัคร': 'Register Date',
        'การอนุมัติ': 'Approval',
        'รออนุมัติสิทธิ์': 'Pending Approval',
        'อนุมัติสิทธิ์': 'Approve',
        'ปฏิเสธ': 'Reject',
        'ไม่มีคำขอที่รอการอนุมัติสิทธิ์เข้าใช้งาน': 'No pending registration requests found.',
        'ชื่อผู้ใช้งาน (Username) *': 'Username *',
        'อีเมลติดต่อ (Email) *': 'Email *',
        'รหัสผ่าน (Password) *': 'Password *',
        'กรอกชื่อผู้ใช้งาน...': 'Enter username...',
        'กรอกรหัสผ่านเริ่มต้น...': 'Enter initial password...',
        'ระดับสิทธิ์ (Role) *': 'Role *',
        'สถานะเริ่มต้น': 'Initial Status',
        'เปิดใช้งาน': 'Active'
      }
    }
  }),
  actions: {
    initLocale() {
      if (process.client) {
        const saved = localStorage.getItem('unifind_locale');
        if (saved === 'en' || saved === 'th') {
          this.locale = saved;
        }
      }
    },
    setLocale(newLocale: 'th' | 'en') {
      this.locale = newLocale;
      if (process.client) {
        localStorage.setItem('unifind_locale', newLocale);
      }
    },
    toggleLocale() {
      const target = this.locale === 'th' ? 'en' : 'th';
      this.setLocale(target);
    },
    t(key: string, params?: Record<string, any>): string {
      if (this.locale === 'th') {
        let text = key;
        if (params) {
          Object.entries(params).forEach(([k, v]) => {
            text = text.replace(new RegExp(`{${k}}`, 'g'), String(v));
          });
        }
        return text;
      }

      const translationMap = this.translations.en as Record<string, string>;
      let text = translationMap[key] || key;

      if (params) {
        Object.entries(params).forEach(([k, v]) => {
          text = text.replace(new RegExp(`{${k}}`, 'g'), String(v));
        });
      }
      return text;
    }
  }
});
