// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/31/2026, 11:45:38 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Phutanes/UTCC/Final_Project/Unifind_Front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Phutanes/UTCC/Final_Project/Unifind_Front/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Phutanes/UTCC/Final_Project/Unifind_Front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Phutanes/UTCC/Final_Project/Unifind_Front/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Phutanes/UTCC/Final_Project/Unifind_Front/plugins/**/*.{js,ts,mjs}","C:/Phutanes/UTCC/Final_Project/Unifind_Front/composables/**/*.{js,ts,mjs}","C:/Phutanes/UTCC/Final_Project/Unifind_Front/utils/**/*.{js,ts,mjs}","C:/Phutanes/UTCC/Final_Project/Unifind_Front/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Phutanes/UTCC/Final_Project/Unifind_Front/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Phutanes/UTCC/Final_Project/Unifind_Front/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Phutanes/UTCC/Final_Project/Unifind_Front/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;