// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/10/2026, 2:49:04 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/ACER/Documents/GitHub/Unifind/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ACER/Documents/GitHub/Unifind/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ACER/Documents/GitHub/Unifind/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ACER/Documents/GitHub/Unifind/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ACER/Documents/GitHub/Unifind/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/ACER/Documents/GitHub/Unifind/frontend/composables/**/*.{js,ts,mjs}","C:/Users/ACER/Documents/GitHub/Unifind/frontend/utils/**/*.{js,ts,mjs}","C:/Users/ACER/Documents/GitHub/Unifind/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ACER/Documents/GitHub/Unifind/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ACER/Documents/GitHub/Unifind/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ACER/Documents/GitHub/Unifind/frontend/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;