// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/1/2026, 4:11:23 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Phutanes/UTCC/Final_Project/Unifind/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Phutanes/UTCC/Final_Project/Unifind/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Phutanes/UTCC/Final_Project/Unifind/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Phutanes/UTCC/Final_Project/Unifind/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Phutanes/UTCC/Final_Project/Unifind/frontend/plugins/**/*.{js,ts,mjs}","C:/Phutanes/UTCC/Final_Project/Unifind/frontend/composables/**/*.{js,ts,mjs}","C:/Phutanes/UTCC/Final_Project/Unifind/frontend/utils/**/*.{js,ts,mjs}","C:/Phutanes/UTCC/Final_Project/Unifind/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Phutanes/UTCC/Final_Project/Unifind/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Phutanes/UTCC/Final_Project/Unifind/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Phutanes/UTCC/Final_Project/Unifind/frontend/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;